#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation

#app_web:
#    resource: "@AppBundle/Controller"
#    type: annotation

#app_api:
#    resource: "@AppBundle/Controller/Api"
#    type: annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_web:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_api:
    resource: "@AppBundle/Controller/Api"
    type:     annotation

rest:
    resource: "@AppBundle/Controller/Api/"
    type:   annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc