# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    jms_serializer.unserialize_object_constructor:
      class: AppBundle\Serializer\ObjectConstructor

    jms_serializer.object_constructor:
      alias: jms_serializer.doctrine_object_constructor